# Generated by Django 2.2.6 on 2020-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the title of the article', max_length=30)),
                ('author', models.CharField(help_text='the author of the article', max_length=30)),
                ('content', models.TextField(help_text='the content of the article')),
                ('description', models.TextField(blank=True, help_text='the description of the article')),
                ('published_date', models.DateTimeField()),
                ('category', models.CharField(help_text='the category of the article', max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
